export const portfolioData = {
  personal: {
    name: "Ganesh Sonawane",
    title: "AI-ML Developer & Backend Engineer",
    email: "ganeshsonawane39773@gmail.com",
    phone: "+91 9373519234",
    location: "Pune, Maharashtra",
    linkedin: "https://linkedin.com/in/ganesh-sonawane-993a63379",
    github: "https://github.com/SonawaneGanes",
    resumeUrl: "https://drive.google.com/file/d/YOUR_RESUME_ID/view",
  },
  about:
    "B.Tech Computer Engineering graduate (CGPA: 8.34/10, Batch 2025) specializing in backend development, AI/ML integration, and enterprise application architecture. Proficient in Java, Python, and full SDLC. Experienced in building scalable REST APIs, microservices, and AI-powered applications with strong DevOps foundation using Docker, CI/CD, and Git.",
  skills: {
    languages: ["Java", "Python", "C++", "Node.js", "JavaScript"],
    backend: [
      "Flask",
      "FastAPI",
      "REST APIs",
      "Microservices",
      "Transaction Management",
    ],
    databases: ["MySQL", "PostgreSQL", "MongoDB"],
    devops: ["Git", "GitHub", "Docker", "Linux", "CI/CD", "Agile/Scrum"],
    ai_ml: [
      "TensorFlow",
      "Scikit-learn",
      "Pandas",
      "NumPy",
      "LLM Integration",
      "RAG",
    ],
    coreCS: [
      "Data Structures & Algorithms",
      "System Design",
      "OOP",
      "Test-Driven Development",
    ],
  },
  experience: [
    {
      id: 1,
      company: "Blue Planet Info Solution Pvt. Ltd.",
      position: "AI-ML Developer Intern",
      location: "Pune",
      period: "Oct 2025 – Present",
      highlights: [
        "Designed and developed backend REST APIs using Python (Flask/FastAPI) with OOP principles and modular design",
        "Applied full SDLC practices from requirements to deployment with Git and Docker containerization",
        "Integrated enterprise data pipelines using Pandas, NumPy for data preprocessing and feature engineering",
        "Collaborated in Agile environments delivering sprint commitments with coding best practices",
      ],
    },
    {
      id: 2,
      company: "YBI Foundation",
      position: "Data Science & AI/ML Intern",
      location: "Remote",
      period: "Oct 2024 – Nov 2024",
      highlights: [
        "Built and evaluated ML models using Python and Scikit-learn",
        "Developed Flask APIs to integrate machine learning models into applications",
        "Performed data cleaning, transformation, and validation using Pandas",
        "Managed structured datasets using MySQL with optimized SQL queries",
      ],
    },
  ],
  projects: [
    {
      id: 1,
      title: "Digital Wallet System",
      subtitle: "Enterprise Backend Application",
      description:
        "Full-stack enterprise backend application demonstrating Java/JEE-equivalent backend development with atomic transaction management, secure PIN-based authentication, and real-time fund transfer capabilities.",
      technologies: ["Flask", "MySQL", "Transaction Management", "REST APIs"],
      keyFeatures: [
        "Atomic transaction management with commit/rollback",
        "Secure PIN-based authentication",
        "Real-time fund transfer system",
        "Input validation and audit trails",
        "Transaction observability dashboard",
      ],
      impact: "Enterprise-grade banking system demonstrating transaction integrity and security",
    },
    {
      id: 2,
      title: "AI Doctor Chatbot",
      subtitle: "Backend API & System Integration",
      description:
        "Scalable REST API backend with LLM integration and structured JSON pipelines for real-time user query handling. Implements RAG-based context handling for improved system reliability and accuracy.",
      technologies: [
        "Flask",
        "LLM Integration",
        "RAG",
        "REST APIs",
        "JSON Processing",
      ],
      keyFeatures: [
        "Scalable REST API architecture",
        "LLM integration with structured JSON pipelines",
        "API versioning",
        "RAG-based context handling",
        "Real-time query processing",
      ],
      impact: "Intelligent healthcare assistant with context-aware responses",
    },
    {
      id: 3,
      title: "Wild Eye AI",
      subtitle: "End-to-End Application Pipeline",
      description:
        "Complete application pipeline combining Python, TensorFlow, and OpenCV with comprehensive data preprocessing and model integration. Achieved 90%+ accuracy through iterative optimization and hyperparameter tuning.",
      technologies: ["Python", "TensorFlow", "OpenCV", "NumPy", "Pandas"],
      keyFeatures: [
        "End-to-end ML pipeline",
        "Data preprocessing and augmentation",
        "Model training and optimization",
        "Hyperparameter tuning",
        "90%+ accuracy achievement",
      ],
      impact: "High-accuracy computer vision system for real-world applications",
    },
    {
      id: 4,
      title: "AI Presentation Generator",
      subtitle: "Automation Tool",
      description:
        "Python automation tool leveraging GPT APIs to generate professional presentations automatically. Containerized with Docker and deployed via CI/CD pipeline, reducing manual effort by 80%.",
      technologies: ["Python", "GPT APIs", "Docker", "CI/CD"],
      keyFeatures: [
        "GPT API integration",
        "Automated presentation generation",
        "Docker containerization",
        "CI/CD deployment",
        "80% efficiency improvement",
      ],
      impact: "80% reduction in manual presentation creation effort",
    },
  ],
  education: [
    {
      id: 1,
      institution: "Dr. Babasaheb Ambedkar Technological University",
      degree: "B.Tech in Computer Engineering",
      period: "2022 – 2025",
      highlights: ["CGPA: 8.34/10", "No Active Backlogs", "Batch 2025"],
    },
    {
      id: 2,
      institution: "Shri Gulabrao Deokar Polytechnic",
      degree: "Diploma in Computer Engineering",
      location: "Jalgaon",
      period: "2019 – 2022",
      highlights: ["Percentage: 73%"],
    },
  ],
  certifications: [
    "Oracle Cloud Generative AI Professional (OCI)",
    "AI Fluency – Anthropic",
    "McKinsey Forward Program",
    "Linux & DevOps Certification",
    "Tata Data Visualization",
  ],
  achievements: [
    "Completed Google GenAI Exchange Program (2025) — Vertex AI, Gemini, Imagen",
    "Delivered 4 end-to-end software projects including enterprise backend, chatbot, CV system, and automation tool",
    "Strong SDLC foundation with Git, Docker, CI/CD, Linux, and Agile practices aligned with IBM DevOps methodology",
  ],
  stats: {
    projectsCompleted: 4,
    yearsExperience: 1,
    internships: 2,
    certifications: 4,
  },
};
